name: Security Pipeline

# RÈGLE : s’exécuter automatiquement sur push ou pull_request
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Étape initiale : Récupération du code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Important pour le Secret Scanning (historique des commits)

      # RÈGLE : installer les dépendances
      - name: Setup Node.js & Install dependencies
        uses: actions/setup-node@v4
        with:
          node-version: '24'
      - run: npm ci

      # RÈGLE : lancer les tests (Objectif : vérifier que l’application fonctionne)
      - name: Run Tests (npm test)
        run: npm test

      # RÈGLE : lancer au moins un scan SAST (Objectif : analyser le code source)
      - name: SAST Scan (Semgrep)
        uses: semgrep/semgrep-action@v1
        with:
          config: p/javascript

      # RÈGLE : lancer un audit des dépendances (Objectif : analyser les dépendances)
      - name: Dependency Audit (SCA - npm audit)
        run: npm audit --audit-level=critical # RÈGLE : échouer en cas de faille critique

      # RÈGLE : lancer un secret scanning (Objectif : détecter les secrets exposés)
      - name: Secret Scanning (Gitleaks)
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # RÈGLE : échouer si un secret est détecté

      # RÈGLE : Lancer un scan DAST (Analyse dynamique de l'application en cours d'exécution)
      - name: Actual DAST Scan (OWASP ZAP)
        run: |
          node index.js &
          sleep 5
          docker run --network="host" -t ghcr.io/zaproxy/zaproxy:stable zap-baseline.py -t http://localhost:3000 || true